apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: aap25-test

resources:
  - 01-namespace.yml
  - 02-operatorgroup.yml
  - 03-subscription.yml
  - 04-aap.yml
  - ../base/installplan-approver

patches:
  - target:
      kind: RoleBinding
      name: installplan-approver
    patch: |-
      apiVersion: rbac.authorization.k8s.io/v1
      kind: RoleBinding
      metadata:
        name: installplan-approver
      subjects:
        - kind: ServiceAccount
          name: installplan-approver
          namespace: aap25-test
